// -------- Endpoints - Users --------//


GET http://localhost:3306/user/getAll
Content-Type: application/json

####
POST http://localhost:3306/user/createUser
Content-Type: application/json

{
    "id": "3",
    "name": "Douglas Will",
    "email": "doug05@aaa.com",
    "password": "12345678"
}


// -------- Endpoints - Posts --------//

###
GET http://localhost:3306/post/getAll
content-type: application/json

###
POST http://localhost:3306/post/createPost
Content-Type: application/json

{
    "photo": "https://picsum.photos/210/310",
    "description": "teste 9",
    "type": "normal",
    "authorId": "1"
}

###
GET http://localhost:3306/post//getById
Content-Type: application/json
Authorization: 0ef1fe82-9de4-4923-a524-228d1015dd25


// -------- Endpoints - Friendships --------//

###
GET http://localhost:3306/friendship/getAll
Content-Type: application/json

###
POST http://localhost:3306/friendship/1
Content-Type: application/json

{
    "friendId": "17d8bcdb-33ab-46bc-8356-3794c5db9bd6"
}
